"""Appointments

Revision ID: 0002
Revises: 0001
Create Date: 2026-01-14 12:12:55.956494

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("therapist_id", sa.UUID(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "completed", "canceled", name="appointmentstatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["therapists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("patients", sa.Column("supabase_user_id", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "patients", ["supabase_user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "patients", type_="unique")
    op.drop_column("patients", "supabase_user_id")
    op.drop_table("appointments")
    # ### end Alembic commands ###
