"""add treatment in appointment

Revision ID: 0005
Revises: 0004
Create Date: 2026-01-14 14:44:23.552551

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, Sequence[str], None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointments", sa.Column("treatment_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "appointments", "treatments", ["treatment_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.drop_column("appointments", "treatment_id")
    # ### end Alembic commands ###
